// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
//  Created by Sam Deane on 08/03/22.
//  All code (c) 2022 - present day, Elegant Chaos Limited.
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

// Reference: https://mod.gib.me/skyrim/functions.html#functions


import Foundation

struct FunctionIndex {
    let index: [Int:Function]
    
    static var instance = FunctionIndex()
    
    init() {
        var index: [Int:Function] = [:]
        for f in Self.events {
            index[f.id] = f
        }
        for f in Self.console {
            index[f.id] = f
        }
        for f in Self.functions {
            index[f.id] = f
        }
        self.index = index
    }
    
    func function(for code: UInt16) -> Function? {
        return index[Int(code) + 4096]
    }

    static let events: [Function] = [
        
        // events
        Function(0, "GameMode"),
        Function(1, "MenuMode", .integer),
        Function(2, ref: true, "OnActivate", .actor),
        Function(3, ref: true, "OnAdd", .container),
        Function(4, ref: true, "OnEquip", .container),
        Function(5, ref: true, "OnUnequip", .container),
        Function(6, ref: true, "OnDrop", .container),
        Function(7, ref: true, "SayToDone", .topic),
        Function(8, ref: true, "OnHit", .actor),
        Function(9, ref: true, "OnHitWith", .unknown(53, "ObjectID")),
        Function(10, ref: true, "OnDeath", .actor),
        Function(11, ref: true, "OnMurder", .actor),
        Function(12, ref: true, "OnCombatEnd"),
        Function(13, ref: true, "Unused"),
        Function(14, ref: true, "Unused2"),
        Function(15, ref: true, "OnPackageStart", .unknown(29, "Package")),
        Function(16, ref: true, "OnPackageDone", abbrev: "OnPackageEnd", .unknown(29, "Package")),
        Function(17, ref: true, "ScriptEffectStart"),
        Function(18, ref: true, "ScriptEffectFinish"),
        Function(19, ref: true, "ScriptEffectUpdate"),
        Function(20, ref: true, "OnPackageChange", .unknown(29, "Package")),
        Function(21, ref: true, "OnLoad"),
        Function(22, ref: true, "OnMagicEffectHit", .unknown(31, "Magic Effect")),
        Function(23, ref: true, "OnSell", .actor),
        Function(24, ref: true, "OnTrigger", .unknown(4, "ObjectReferenceID")),
        Function(25, ref: true, "OnStartCombat", .actor),
        Function(26, ref: true, "OnTriggerEnter", .unknown(4, "ObjectReferenceID")),
        Function(27, ref: true, "OnTriggerLeave", .unknown(4, "ObjectReferenceID")),
        Function(28, ref: true, "OnActorEquip", .unknown(21, "ObjectID")),
        Function(29, ref: true, "OnActorUnequip", .unknown(21, "ObjectID")),
        Function(30, ref: true, "OnReset"),
        Function(31, ref: true, "OnOpen"),
        Function(32, ref: true, "OnClose"),
        Function(33, ref: true, "OnGrab"),
        Function(34, ref: true, "OnRelease"),
        Function(35, ref: true, "OnDestructionStageChange", .integer),
    ]
    
    static let console: [Function] = [
        
        // console
        Function(256, "Show", abbrev: "TST", .float, description: "Show global scripts and variables."),
        Function(257, ref: true, "ShowVars", abbrev: "SV", description: "Show variables on object. [player-&gt;sv]"),
        Function(258, "ShowGlobalVars", abbrev: "SGLV", description: "Show all global variables."),
        Function(259, "ShowQuestVars", abbrev: "SQV", .quest, description: "Show quest variables. [svq QuestID]"),
        Function(260, "ShowQuests", abbrev: "SQ", description: "List quests."),
        Function(261, "ShowQuestAliases", .quest, description: "Show quest aliases. [ShowQuestAliases QuestID]"),
        Function(262, "SetPapyrusQuestVar", abbrev: "SETPQV", .quest, .string, .string, description: "Set a Papyrus property on the specified quest."),
        Function(263, "SetPapyrusVar", abbrev: "SETPV", .string, .string, description: "Set a Papyrus property on the selected ref."),
        Function(264, "SetQuestAliases", .quest, description: "Set quest aliases. [SetQuestAliases QuestID]"),
        Function(265, "ClearQuestAliases", .quest, description: "Clears quest aliases. [ClearQuestAliases QuestID]"),
        Function(266, "ToggleCombatStats", abbrev: "TCS"),
        Function(267, "ToggleSafeZone", abbrev: "TSZ", description: "Display the television 85% safe zone."),
        Function(268, "ToggleAI", abbrev: "TAI", .actor),
        Function(269, "ToggleCollisionGeometry", abbrev: "TCG", description: "Show collision geometry."),
        Function(270, "ToggleMaterialGeometry", abbrev: "TMG", description: "Show material geometry."),
        Function(271, "ToggleStairsGeometry", abbrev: "TSG", description: "Show stairs geometry."),
        Function(272, "ToggleBorders", abbrev: "TB", description: "Show border lines for each cell."),
        Function(273, "ToggleSky", abbrev: "TS"),
        Function(274, "ToggleWireframe", abbrev: "TWF", description: "Show the world as wireframe."),
        Function(275, "ToggleCollision", abbrev: "TCL"),
        Function(276, "ToggleDebugText", abbrev: "TDT", description: "Show debug numbers on the screen."),
        Function(277, "ToggleMenus", abbrev: "TM", description: "Hide all the menus. Used for taking screen shots."),
        Function(278, "TogglePrimitives", abbrev: "TPR"),
        Function(279, "ShowScenegraph", abbrev: "SSG", description: "Create a window with the full game scene graph or the scene graph of the selected reference."),
        Function(280, "ShowScenegraph", abbrev: "SFSG", description: "Create a window with the full game scene graph, open to the node corresponding to the selected reference (if any)."),
        Function(281, "ToggleMagicStats", abbrev: "TMS"),
        Function(282, ref: true, "ShowAnim", abbrev: "SA", description: "Show Animation and Actor status."),
        Function(283, "Show1stPerson", abbrev: "S1ST", description: "Show the 1st person Model from the 3rd person camera. If in 3rd person mode it will show both."),
        Function(284, "Help", .string, .integer, description: "Show this help."),
        Function(285, "ToggleNavMesh", abbrev: "TNM", .integer, description: "Toggle blocked display."),
        Function(286, "TogglePathLine", abbrev: "TPL", .string, description: "Toggle path display."),
        Function(287, "PickRefByID", abbrev: "PRID", .unknown(4, "ObjectReferenceID"), description: "Select a reference by id for the console."),
        Function(288, "SetLightingPasses", abbrev: "SLP", .string, description: "4 (0/1) values. amb|diff|tex|spec ex: 1010"),
        Function(289, "ToggleLODLand", abbrev: "TLL", .string, .string, .string, .string),
        Function(290, "ToggleMapEffect", abbrev: "TME", .string),
        Function(291, "SetLODObjectDistance", abbrev: "SLOD", .float, .float, .float, .float),
        Function(292, "ToggleGrassUpdate", abbrev: "TGU"),
        Function(293, "CenterOnCell", abbrev: "COC", .string),
        Function(294, "SetGameSetting", abbrev: "SetGS", .string, .string),
        Function(295, "SetINISetting", abbrev: "SetINI", .string, .string, description: "&quot;setting:category&quot; value"),
        Function(296, "GetINISetting", abbrev: "GetINI", .string, description: "&quot;setting:category&quot;"),
        Function(297, "CenterOnExterior", abbrev: "COE", .integer, .integer),
        Function(298, ref: true, "CalcPathToPoint", abbrev: "P2P"),
        Function(299, ref: true, "CalcLowPathToPoint", abbrev: "LP2P", .integer, .integer, .integer, description: "ignore locks, allow disabled doors, ignore min use"),
        Function(300, "SetFog", .integer, .integer, description: "2 floats, start and end depths"),
        Function(301, "SetClipDist", .float, description: "float, new clip distance"),
        Function(302, "ToggleShadowVolumes", abbrev: "TSV"),
        Function(303, "SetImageSpaceGlow", abbrev: "SISG", .integer, .float, .float, .float),
        Function(304, "ToggleDetection", abbrev: "TDETECT"),
        Function(305, "ToggleHighProcess", abbrev: "THIGHPROCESS"),
        Function(306, "ToggleLowProcess", abbrev: "TLOWPROCESS"),
        Function(307, "ToggleMiddleLowProcess", abbrev: "TMLOWPROCESS"),
        Function(308, "ToggleMiddleHighProcess", abbrev: "TMHIGHPROCESS"),
        Function(309, "ToggleAiSchedules", abbrev: "TAIS"),
        Function(310, ref: true, "SpeakSound", .string("Filename"), .integer("Emotion"), .integer("EmotionValue")),
        Function(311, "BetaComment", abbrev: "BC", .string, description: "Add comment to [General] 'sBetaCommentFile' file. NOTE: select object first. ‘This rock is too high’]"),
        Function(312, "GameComment", abbrev: "GC", .string, description: "Adds a comment about the game to the GameCommentDB. (Ex. This monster is too hard)"),
        Function(313, "ToggleCellNode", abbrev: "TCN", .integer, description: "Toggle 3D for a Cell child node: 0-Actor, 1-Marker, 2-Land, 3-Water, 4-Static, 5-Active"),
        Function(314, "ToggleTrees", abbrev: "TT", description: "Turn trees on/off"),
        Function(315, "SetCameraFOV", abbrev: "FOV", .float, .float, description: "Change the camera's field of view (in deg): default 75"),
        Function(316, "ToggleGodMode", abbrev: "TGM", description: "Toggle God mode"),
        Function(317, "RefreshShaders", abbrev: "RS", .string, description: "Reload HLSL shaders from disk"),
        Function(318, "ToggleScripts", abbrev: "TSCR", description: "Turn Script processing on/off"),
        Function(319, "ToggleConversations", abbrev: "TCONV", description: "Toggle conversation stats"),
        Function(320, "ToggleFullHelp", abbrev: "TFH", description: "Toggle Full Help"),
        Function(321, "ShowQuestLog", abbrev: "SQL", .integer, description: "Show Quest Log"),
        Function(322, "ShowFullQuestLog", abbrev: "SFQL", .quest, description: "Show all log entries for a single quest"),
        Function(323, "DumpTexturePalette", abbrev: "DTP", .string, description: "Dump texture palette contents to file param is sort type   f-filename, s-size, c-count"),
        Function(324, "DumpModelMap", abbrev: "DMM", .string, description: "Dump model map contents to file"),
        Function(325, "CenterOnWorld", abbrev: "COW", .unknown(27, "WorldSpace"), .integer("Cell X"), .integer("Cell Y"), description: "[COW worldname -10 5]"),
        Function(326, "ToggleGrass", abbrev: "TG", description: "Toggle grass display."),
        Function(327, "CreateGrassAt", abbrev: "cga", .float, .float),
        Function(328, ref: true, "AddFaceAnimNote", abbrev: "AFAN", .string),
        Function(329, "RefreshINI", abbrev: "REFINI", description: "Refresh INI settings from file."),
        Function(330, "ToggleEmotions", abbrev: "temo", description: "Toggle NPC facial emotions."),
        Function(331, "AddDecal"),
        Function(332, "TestCode", .float, .float),
        Function(333, "PlayerSpellBook", abbrev: "psb", description: "Add all spells to player."),
        Function(334, "PrintAiList", abbrev: "pai", description: "Printed Ai Lists."),
        Function(335, "ShowQuestTargets", abbrev: "SQT", description: "Show current quest targets"),
        Function(336, "HairTint", .integer, .integer, .integer, description: "3 ints, RGB"),
        Function(337, "SaveGame", abbrev: "save", .string, .integer, description: "SaveGame &lt;filename&gt;"),
        Function(338, "LoadGame", abbrev: "load", .string, .integer, description: "LoadGame &lt;filename&gt;"),
        Function(339, "TestAllCells", abbrev: "TAC", .integer, description: "Test All Cells (0 - stop, 1 - start, 2 - interiors, 3 - current world)"),
        Function(340, "RenderTestCell", abbrev: "rtc", description: "runs Render Test on player's current parent cell"),
        Function(341, "RenderTestHere", abbrev: "rth", description: "runs Render Test on player's current position"),
        Function(342, "SaveWorld", .string, description: "Save hkWorld &lt;filename&gt;"),
        Function(343, "ReloadCurrentClimate", abbrev: "rcc", description: "Reloads values from the current climate"),
        Function(344, "ReloadCurrentWeather", abbrev: "rcw", description: "Reloads values from the current weather"),
        Function(345, "TestSeenData", abbrev: "tsd", description: "Visually displays the current seen data"),
        Function(346, "TestLocalMap", abbrev: "tlm", .integer, description: "Simulates the local map. (1 or 0 for FOW on or off)"),
        Function(347, "MoveToQuestTarget", abbrev: "movetoqt", .quest, .integer, description: "Move player to current quest target."),
        Function(348, "PrintNPCDialog", abbrev: "pdialog", description: "Prints NPC dialog"),
        Function(349, "ShowSubtitle", .integer, description: "show all dialog subtitles (1 shows always, 0 hides always)"),
        Function(350, "ShowRenderPasses", abbrev: "srp", description: "display render passes for the next frame"),
        Function(351, "FreezeRenderAccumulation", abbrev: "fra", description: "only re-render geometry visible during this frame"),
        Function(352, "ToggleOcclusion", abbrev: "tocc", description: "toggle occlusion query for geometry"),
        Function(353, "OutputMemContexts", abbrev: "omc", .string, description: "Output Mem Context info to a file"),
        Function(354, "OutputMemStats", abbrev: "oms", .string, description: "Output Mem Stats info to a file"),
        Function(355, "SetMemCheckPoint", abbrev: "smcp", .integer, .string, description: "Set the current memory checkpoint (value, optional context name)"),
        Function(356, "GetMemCheckPoint", abbrev: "gmcp", .string, description: "Get the current memory checkpoint (optional context name)"),
        Function(357, "IncMemCheckPoint", abbrev: "imcp", .string, description: "Increment the current memory checkpoint (optional context name)"),
        Function(358, "OutputAllocations", abbrev: "outalloc", .string, .string, .integer, .integer, description: "Output memory allocations (file, optional context name, optional start context, optional end context)"),
        Function(359, "AddWatchAddress", abbrev: "awa", .string, .integer, description: "Adds an address range to watch out for."),
        Function(360, "RemoveWatchAddress", abbrev: "rwa", .string, description: "Removes an address range that we no longer want to watch."),
        Function(361, "ToggleDetectionStats", abbrev: "tds", .actor, description: "Show the detection stats of the current seletected Ref."),
        Function(362, "SetTargetRefraction", abbrev: "str", .float, description: "Sets the refractive value of the target"),
        Function(363, "SetTargetRefractionFire", abbrev: "strf", .float, .integer("Int"), description: "Sets the refractive fire value of the target"),
        Function(364, "ToggleRefractionDebug", abbrev: "trd", description: "Toggles refraction debug render texture"),
        Function(365, "ToggleCharControllerShape", abbrev: "TCCS", description: "Toggle char controller shape type."),
        Function(366, ref: true, "ShowHeadTrackTarget", abbrev: "SHeadT", description: "Show the head track target if set from look function"),
        Function(367, "SetCinematicParam", abbrev: "SCP", .float, .float, .float, description: "Sets various values for the imagespace cinematics"),
        Function(368, "SetTintParam", abbrev: "STP", .float, .float, .float, .float, description: "Sets various values for the imagespace tint"),
        Function(369, "SetHDRParam", abbrev: "SHP", .float, .float, .float, .float, .float, .float, .float, .float, .float, description: "Sets various values for the HDR shader"),
        Function(370, ref: true, "VisualRefPosition", abbrev: "VRP", description: "Places and axis object at the ref position."),
        Function(371, ref: true, "ShowPivot", abbrev: "SP", description: "Puts a temporary yellow plus at the pivot point of the selected reference."),
        Function(372, "PrintHDRParam", abbrev: "PHP", description: "Prints current HDR settings."),
        Function(373, "ToggleHDRDebug", abbrev: "THD", description: "Toggles HDR debug textures."),
        Function(374, "RevertWorld", abbrev: "rw", description: "Revert the world"),
        Function(375, "OutputArchiveProfile", abbrev: "oap", .string, description: "Output Archive profile info to a file"),
        Function(376, "QuitGame", abbrev: "qqq", description: "Exit game without going through menus."),
        Function(377, "SaveIniFiles", abbrev: "saveini", description: "Writes all the .ini files."),
        Function(378, "SetDebugText", abbrev: "sdt", .string, .integer, description: "Sets which debug text is shown."),
        Function(379, "ToggleLiteBrite", abbrev: "tlb", description: "Toggles lite brite render mode."),
        Function(380, "RunMemoryPass", abbrev: "rmp", .integer, description: "Runs a cleanup memory pass"),
        Function(381, "ResetMemContexts", abbrev: "rmc", description: "Reset Max Mem Contexts"),
        Function(382, "ToggleWaterSystem", abbrev: "TWS", description: "Toggles the water system"),
        Function(383, "ToggleWaterRadius", abbrev: "TWR"),
        Function(384, "ShowWhoDetectsPlayer", abbrev: "SWDP", description: " Show who detects the player"),
        Function(385, "ToggleCombatAI", abbrev: "tcai", description: "Toggles ALL Combat AI"),
        Function(386, "ToggleFlyCam", abbrev: "tfc", .integer, description: "Toggles the Free Fly camera (UFO cam)."),
        Function(387, "ModWaterShader", abbrev: "mws", .string, .float, description: "Modifies water shader settings"),
        Function(388, "WaterColor", abbrev: "mwc", .integer, .float, .float, .float, description: "Modifies water color"),
        Function(389, "BeginTrace", abbrev: "bt", description: "Creates a trace file (Xenon only)"),
        Function(390, "RunCellTest", abbrev: "rct", .integer, description: "Runs a cell test"),
        Function(391, "StartAllQuests", abbrev: "saq", description: "Starts all quests"),
        Function(392, "CompleteAllQuestStages", abbrev: "caqs", description: "Sets all quest stages"),
        Function(393, "ToggleFogOfWar", abbrev: "TFOW", description: "Turns fog of war on or off."),
        Function(394, "OutputLocalMapPictures", abbrev: "OLMP", description: "Writes out the current local map."),
        Function(395, "SetGamma", abbrev: "sg", .float, description: "Sets new gamma ramp."),
        Function(396, "WasteMemory", abbrev: "wm", .float, description: "Allocates some memory (in MB)."),
        Function(397, "ClearAdaptedLight", abbrev: "cal", description: "Clears the HDR adapted light texture"),
        Function(398, "ToggleCastShadows", abbrev: "tsh", .integer),
        Function(399, "SetHudGlowConstants", abbrev: "shgc", .float, .float, .float, .float, description: "Set parameters for HUD glow."),
        Function(400, "CloseFile", .string),
        Function(401, "SetTreeMipmapBias", abbrev: "stmb", .float, .float, description: "Set mipmap LOD bias values for tree billboards."),
        Function(402, "SendSherlockDebugText", abbrev: "ssdt", .string),
        Function(403, "OutputMemStats", abbrev: "omsfw", .string, description: "Output Mem Stats info to a file"),
        Function(404, "PlayExplosion", description: "Plays explosion seq in selected obj"),
        Function(405, "SetMaxAniso", abbrev: "sma", .float, description: "Sets Depth of Field focal distance"),
        Function(406, "SetMeshLODLevel", abbrev: "smll", .float, description: "Sets Depth of Field range"),
        Function(407, "SetTargetDOF", abbrev: "stdof", description: "Sets the depth of field based on the target"),
        Function(408, "ToggleFullScreenMotionBlur", abbrev: "tfsmb", description: "Toggles Full screen motion blur"),
        Function(409, "SetTriLinearThreshold", abbrev: "stlt", .float, description: "Set the motion blur params"),
        Function(410, "ToggleFootIK", abbrev: "tfik", description: "Toggles Foot IK system"),
        Function(411, ref: true, "SetVel", .unknown(8, "Axis"), .float, description: "Sets Velocity on a reference"),
        Function(412, ref: true, "DebugCombatBehavior", abbrev: "dcb", description: "Debugs the combat behavior on an actor"),
        Function(413, "ToggleCombatDebug", abbrev: "tcd", .string, description: "Toggles combat debug info"),
        Function(414, "TogglePathingInfoFunction", abbrev: "TPI", description: "Toggle pathing information."),
        Function(415, ref: true, "ShowInventory", abbrev: "inv", description: "Shows reference inventory"),
        Function(416, "ResetPerformanceTimers", abbrev: "rpt", description: "Resets the performance timers"),
        Function(417, "ToggleDebugDecal", abbrev: "TDD", .integer, description: "Toggle debug displays for decal creation : 0-Wireframe, 1-Solid, 2-Occlusion Query, 3-Transform"),
        Function(418, "ToggleDecalRendering", abbrev: "TDR", description: "Toggle decal rendering"),
        Function(419, "SetImageSpaceModifiersEnable", abbrev: "sisme", .integer, description: "Set imagespace modifiers enable: 0-Off, 1-On"),
        Function(420, "SetUFOCamSpeedMult", abbrev: "sucsm", .float, description: "Set speed mult for free camera."),
        Function(421, "ToggleTestLight", abbrev: "TTL", .integer, .float, .float, description: "Toggle test light (radius, magnitude)."),
        Function(422, "PlaceLocationMarker", abbrev: "plm", .float("X"), .float("Y"), .float("Z"), .string("Name"), .integer("Color"), description: "PlaceLocationMarker x y z (optional name) (optional color )"),
        Function(423, "ClearLocationMarkers", abbrev: "clm"),
        Function(424, "ToggleMultiboundCheck", abbrev: "mbc", description: "Toggle all Multibound check functionality"),
        Function(425, "ToggleGrabIK", abbrev: "tgik", description: "Toggles Grab IK system"),
        Function(426, "ToggleLookIK", abbrev: "tlik", description: "Toggles Look IK system"),
        Function(427, "ToggleRagdollAnim", abbrev: "tra", description: "Toggles Ragdoll Anim system"),
        Function(428, "AddOcclusionPlane", abbrev: "AOP", .float, .float, description: "Add Occlusion plane (x size, y size)."),
        Function(429, "SetGlobalRadialBlur", abbrev: "sgrb", .float, .float, .float, .float, .float, description: "Set parameters for the global radial blur"),
        Function(430, "OutputTextureUseMap", abbrev: "OTUM", .string, description: "Writes out texture use map data to file."),
        Function(431, "ClearScreenBlood", abbrev: "csb", description: "Clear screen blood"),
        Function(432, "ResetDialogueFlags", abbrev: "rdf", description: "Debug resets SayOnce, TalkedToPc, etc."),
        Function(433, ref: true, "GetActorValueInfo", abbrev: "GetAVInfo", .actorValue, description: "Get detailed an actor value info. [player.getav luck]"),
        Function(434, "ToggleBoundVisGeom", abbrev: "tbvg", description: "Toggles bound visualization for a ref"),
        Function(435, "SetConsoleOuputFile", abbrev: "scof", .string, description: "Sets the given file as target for console output."),
        Function(436, "IgnoreRenderPass", abbrev: "irp", .integer, .integer, description: "Ignore the given renderpass"),
        Function(437, "PlayVATSCameras", abbrev: "pvc", .string, description: "Play this set of VATS cameras for the next VATS playback."),
        Function(438, "SetTargetFalloff", abbrev: "stfo", .float, .float, .float, .float, description: "Sets the falloff of the target"),
        Function(439, "ToggleActorMover", abbrev: "tam", description: "Toggles actor movement through pathing system"),
        Function(440, "CopySaves", abbrev: "CopySaves", .string, description: "Copy save games from the host machine or a memory stick (ms)."),
        Function(441, "DrawSkeleton", abbrev: "das", .integer, .integer, .integer, description: "Enables skeleton drawing"),
        Function(442, "ToggleEOFImageSpace", abbrev: "teofis", description: "Toggles end of frame imagespace effects"),
        Function(443, "ForceFileCache", abbrev: "ffc", description: "Enumerates Miles samples and streams"),
        Function(444, "DumpNiUpdates", abbrev: "dnu", description: "Dumps the next frame's calls to NiNode/NiAVObject::UpdateDownwardPass to NiDump*.xls (only Debug/PIX 360 builds)"),
        Function(445, "TestDegrade", .integer, description: "degrades the specified number of MB of textures. negative values degrade all possible. (only 360 builds)"),
        Function(446, "ToggleDepthBias", abbrev: "tdb", description: "toggles depth bias for decals on or off"),
        Function(447, "ToggleSPURenderBatch", abbrev: "tSPURB", description: "toggles the SPU render batch on or off"),
        Function(448, "ToggleSPUTransformUpdate", abbrev: "tSPUTU", description: "toggles the SPU transform update on or off"),
        Function(449, "ToggleSPUCulling", abbrev: "tSPUC", description: "toggles the SPU culling on or off"),
        Function(450, "ModifyFaceGen", abbrev: "mfg", .string, .integer, .integer, description: "Modify FaceGen Functionality"),
        Function(451, "ForceRSXCrash", abbrev: "fRSX", description: "Forces an RSX crash"),
        Function(452, "SetEmitterParticleMax", .integer, description: "Sets the maximum number of particles emitted by a non-master particle system emitter"),
        Function(453, "SetMPSParticleMax", .integer, description: "Sets the maximum number of particles emitted by master particle system emitter set"),
        Function(454, "SetTaskThreadSleep", .integer, description: "Sets the task thread sleep value (-1 to disable)."),
        Function(455, "SetTaskThreadUpdateSleep", .integer, description: "Sets the task thread update sleep value (-1 to disable)."),
        Function(456, "EvalActorTextures", abbrev: "EAT"),
        Function(457, "CreateSaveData", abbrev: "createsaves", .integer, .integer, description: "Creates save data."),
        Function(458, "CreateGameData", .string, .integer, description: "Creates game data."),
        Function(459, "LoadFlashMovie", .string, description: "Loads a Flash movie for the GUI"),
        Function(460, "ShowMenu", .string, description: "Show or create a menu"),
        Function(461, "HideMenu", .string, description: "Hide or close a menu"),
        Function(462, ref: true, "RecvAnimEvent", abbrev: "rae", .string, .string, description: "Simulate recieving an animation event from an animation graph."),
        Function(463, "RunConsoleBatch", abbrev: "bat", .string, description: "Run a console batch file"),
        Function(464, "LTGraph", abbrev: "LTGraph", .string, description: "Sets the input-to-player movement graph"),
        Function(465, "RTGraph", abbrev: "RTGraph", .string, description: "Sets the input-to-camera movement graph"),
        Function(466, "ToggleHeapTracking", abbrev: "THT", description: "Toggle Heap Tracking"),
        Function(467, "TogglePoolTracking", abbrev: "TPT", description: "Toggle Pool Tracking"),
        Function(468, "RumbleManager", abbrev: "RM", .float, .float, .float, .float, description: "RumbleManager"),
        Function(469, "InstallMemoryTracker", abbrev: "IMT", .string, description: "Install Memory Tracker"),
        Function(470, "UninstallMemoryTracker", abbrev: "UMT", description: "Uninstall Memory Tracker"),
        Function(471, "CheckMemory", abbrev: "chkmem", description: "Check Memory"),
        Function(472, "SetStackDepth", abbrev: "SSD", .integer, description: "Set Stack Depth"),
        Function(473, ref: true, "PathToRef", abbrev: "PTR", .unknown(4, "TESObjectREFR"), description: "Force actor to path to reference."),
        Function(474, "StartAIControlledRobotTest", abbrev: "SPTP", .string, .string, .string, description: "Starts player pathing memory test."),
        Function(475, "TestHandleManagerWarnAndKillSDM", abbrev: "THMWAKS", description: "Purely for testing: lists every un-destroyed handle, then destroys it."),
        Function(476, ref: true, "SetFaceTarget", abbrev: "SFT", .unknown(4, "TESObjectREFR"), description: "Force actor to face a reference."),
        Function(477, "PrecomputedLOSGeneration", abbrev: "plg", .string, .string, .string),
        Function(478, "PrecomputedLOSDebug", abbrev: "pld", .string, .string, .string),
        Function(479, ref: true, "SetPathSprinting", abbrev: "SPS", .integer, description: "Force actor to sprint."),
        Function(480, ref: true, "SetAnimGraphVar", abbrev: "sgv", .string, .string, .string, .string, .string, description: "Set an animation graph variable."),
        Function(481, "SetTreeTrunkFlexibility", abbrev: "STSTF", .float, description: "Set the flexibility of trees trunk."),
        Function(482, "SetTreeBranchFlexibility", abbrev: "STSBF", .float, description: "Set the flexibility of trees branches."),
        Function(483, "SetTreeBranchAnimationRange", abbrev: "STSBR", .integer, .integer, description: "Restrict the range of tree branch animations."),
        Function(484, "SetTreeLeafFlexibility", abbrev: "STSLF", .float, description: "Set the flexibility of trees leaves."),
        Function(485, "SetTreeLeafAmplitude", abbrev: "STSLAMP", .float, description: "Set the amplitude of trees leaves."),
        Function(486, "SetTreeLeafFrequency", abbrev: "STSLFRQ", .float, description: "Set the frequency of trees leaves."),
        Function(487, "SetTreeWindDirection", abbrev: "STSWD", .float, .float, description: "Set the tree system wind direction."),
        Function(488, "SetTreeWindMagnitude", abbrev: "STSWM", .float, description: "Set the tree system wind magnitude."),
        Function(489, "SetBloodParam", abbrev: "SBP", .string, .float, description: "Set blood parameters."),
        Function(490, "RegisterPrefix", abbrev: "RPRFX", .string, description: "Register all resources at a path prefix."),
        Function(491, "ToggleEventLog", abbrev: "TEL", description: "Show a log of misc. events for the selected debug REFR."),
        Function(492, "ExportPerfTrackingData", abbrev: "EPTD", description: "Export performance monitor tracking data to a file."),
        Function(493, "DisplayGraphVariable", abbrev: "dgv", .string, description: "Gives control of variable filters used on the animation debug text page."),
        Function(494, ref: true, "ToggleMotionDriven", abbrev: "TMD", .integer, description: "Toggles motion driven animation"),
        Function(495, ref: true, "ToggleControlsDriven", abbrev: "TC", .integer, description: "Toggles controls driven character"),
        Function(496, "ToggleGUIOverlay", abbrev: "TGO", description: "Toggles the graphical overlay"),
        Function(497, "ModifyGUIOverlay", abbrev: "MGO", .string, .string, .integer, .integer, description: "Modifies a graphical overlay"),
        Function(498, ref: true, "SetActionComplete", abbrev: "SAC", description: "Sets all active actions on actor in scene complete"),
        Function(499, "SetConsoleScopeQuest", abbrev: "SSQ", .quest, description: "Sets the scope quest for all console functions. No param clears current scope quest."),
        Function(500, "GetDistanceFromActorsPath", abbrev: "GDFAP", .unknown(4, "TESObjectREFR"), description: "Prints out the distance from a reference to an actor's path."),
        Function(501, "ClearConsole", abbrev: "clear", description: "Clears the console log"),
        Function(502, "ToggleMarkers", abbrev: "TMK", description: "Toggle markers"),
        Function(503, "KillAllProjectiles", abbrev: "kap", description: "Kill all projectiles"),
        Function(504, "PlayTerrainEffect", abbrev: "PTFX", .string, description: "Plays a terrain effect at target REFR"),
        Function(505, "CellInfo", description: "Toggle Cell Info"),
        Function(506, "Textures", abbrev: "tx", description: "Toggle Texture Info"),
        Function(507, "Timing", abbrev: "FPS", description: "Toggle Timing Info"),
        Function(508, "Polygons", abbrev: "Polys", description: "Toggle Mesh Render Info"),
        Function(509, "Actors", abbrev: "Actors", description: "Toggle Actor Info"),
        Function(510, "Quest", abbrev: "Quest", description: "Toggle Quest Event Info"),
        Function(511, "Particles", abbrev: "Particles", description: "Toggle Particle Info"),
        Function(512, "Memory", description: "Toggle Memory Info"),
        Function(513, ref: true, "ShowNodes", .string, description: "Show nodes- [All], [Off]"),
        Function(514, "SaveDebugTextPages", abbrev: "SaveDTP", description: "Save Debug Text Pages settings to .ini file."),
        Function(515, "OutputFixedStringTable", abbrev: "OFST", description: "Output the fixed string table to a file."),
        Function(516, "AttachPapyrusScript", abbrev: "APS", .string, .string, description: "Attaches a papyrus script to a reference"),
        Function(517, "SaveHavokSnapshot", abbrev: "SHS", .string, .integer, description: "Saves a Havok snapshot of the hkpWorld the player is currently in"),
        Function(518, ref: true, "SetNPCWeight", abbrev: "SNPCW", .float, description: "[0-100]: Sets the weight of an NPC and reloads his 3D to visualize the weight change"),
        Function(519, "ShowClosestLocationForSphere", abbrev: "SCLFS", .float, .float, .integer("Int"), description: "Finds the closest location where a sphere can fit in the navmesh, and displays it"),
        Function(520, "PrintShaderMacros", abbrev: "PSM", .string, .string, description: "Given a shader and technique ID, prints the macros used to compile its shader."),
        Function(521, "ToggleAudioOverlay", abbrev: "TAO", description: "Toggle the Audio Debug Overlay."),
        Function(522, "TogglePapyrusLog", abbrev: "TPLog", description: "Toggle the Papyrus Log Overlay."),
        Function(523, "ToggleContextOverlay", abbrev: "TCO", description: "Toggle the Context Overlay."),
        Function(524, "ForceOutOfMemory", abbrev: "FOOM", description: "Forces an OOM state."),
        Function(525, "ToggleMovement", abbrev: "TMOVE", description: "Toggles all actor movement"),
        Function(526, "ToggleAnimations", abbrev: "TANIM", description: "Toggles all actor animations"),
        Function(527, "SetWarning", .string, .integer, description: "Params: Name [0/1]. 0 is default for 2nd param."),
        Function(528, "TestFadeNodes", abbrev: "TestFN"),
        Function(529, "ShowLowMaxHeights", abbrev: "slmh", .integer, .integer),
        Function(530, "ShowHighMaxHeights", abbrev: "shmh", .integer),
        Function(531, "EnableStoryManagerLogging", abbrev: "esml", .string, description: "Enable story manager logging."),
        Function(532, "SetFramebufferRange", abbrev: "sfbr", .float, description: "Set frambuffer range"),
        Function(533, "DumpPapyrusStacks", abbrev: "dps", description: "Dumps all Papyrus stack information to the log"),
        Function(534, "DumpPapyrusUpdates", abbrev: "dpu", description: "Dumps all Papyrus update registrations to the log"),
        Function(535, ref: true, "DisplayLookIKDebug", abbrev: "dlik"),
        Function(536, "SoundCatMod", abbrev: "scm", .unknown(79, "SoundCategory"), .string, .float, description: "In-game control of sound categories."),
        Function(537, "RunCompaction", abbrev: "rcmpct", description: "Run a pass of compaction if possible."),
        Function(538, "ToggleAnimatorCam", abbrev: "animcam", description: "Toggles a 3rd-person camera mode designed for animators' ease-of-use"),
        Function(539, "ToggleImmortalMode", abbrev: "TIM", description: "Toggle Immortal mode"),
        Function(540, "SetSubgraphToDebug", abbrev: "sgd", .integer, description: "Subgraph To Debug"),
        Function(541, "EnableRumble", .integer),
        Function(542, "HavokVDBCapture", abbrev: "vdbcapture", .string, .integer, description: "Havok VDB Capture"),
        Function(543, "ToggleMapCam", abbrev: "tmc", description: "toggle a view mode similar to the map camera for debugging"),
        Function(544, "ToggleNavmeshInfo", abbrev: "tni", description: "toggle a view mode similar to the map camera and displays navmesh infos"),
        Function(545, ref: true, "PlaySyncAnim", abbrev: "syncanim", .string, .unknown(4, "ObjectReferenceID"), description: "Play Sync Anim"),
        Function(546, "SetFormKnown", .string, .integer, description: "Sets the known flag on a form"),
        Function(547, "SetDebugQuest", .quest, .integer, .integer("State"), description: "Sets the quest to be the only one startable for its event type."),
        Function(548, "SetQuestAliasLogging", abbrev: "sqal", .quest, .integer, description: "Turns alias logging on/off for a quest."),
        Function(549, "SetRace", .string, description: "Sets the passed in actor's race."),
        Function(550, "FindForm", abbrev: "find", .string, .string, description: "Find a form"),
        Function(551, "StartPapyrusScriptProfile", abbrev: "StartPSP", .string, description: "Starts profiling a Papyrus script."),
        Function(552, "StopPapyrusScriptProfile", abbrev: "StopPSP", .string, description: "Stops profiling a Papyrus script."),
        Function(553, "StartPapyrusFormProfile", abbrev: "StartPFP", .unknown(62, "Form"), description: "Starts profiling Papyrus scripts on a form."),
        Function(554, "StopPapyrusFormProfile", abbrev: "StopPFP", .unknown(62, "Form"), description: "Stops profiling Papyrus scripts on a form."),
        Function(555, "PrintQuestSceneInfo", abbrev: "PrintS", .quest, description: "Prints to the Quest Inf file the current state of scenes."),
        Function(556, ref: true, "IsInvulnerable", abbrev: "isinv", description: "Is the actor invulnerable?"),
        Function(557, "ExportInventoryItemInfo", abbrev: "eiii", .integer),
        Function(558, "CollisionMesh", abbrev: "colmesh", description: "Toggle Mesh Collision Info"),
        Function(559, "IsolateRendering", abbrev: "ir"),
        Function(560, "ToggleWaterCurrentGeometry", abbrev: "twcg", .integer),
        Function(561, ref: true, "PerformAction", abbrev: "pa", .unknown(83, "Action")),
        Function(562, "StartTrackPlayerDoors", abbrev: "StartTPD"),
        Function(563, "StopTrackPlayerDoors", abbrev: "StopTPD"),
        Function(564, "CheckPlayerDoors", abbrev: "CheckPD", .integer),
        Function(565, "ToggleSPUMovement", abbrev: "tSPUM", description: "toggles the SPU movement on or off"),
        Function(566, "SetInChargen", .integer, .integer, .integer),
        Function(567, "ClearAchievement", .integer),
    ]
    
    static let functions: [Function] = [
        
        // functions
        Function(4096, ref: true, "GetWantBlocking"),
        Function(4097, ref: true, "GetDistance", .unknown(4, "ObjectReferenceID")),
        Function(4098, ref: true, "AddItem", .unknown(53, "ObjectID"), .integer("Count"), .integer("Flag")),
        Function(4099, "SetEssential", .unknown(25, "Actor Base"), .integer),
        Function(4100, ref: true, "Rotate", .unknown(8, "Axis"), .integer("Speed")),
        Function(4101, ref: true, "GetLocked"),
        Function(4102, ref: true, "GetPos", .unknown(8, "Axis")),
        Function(4103, ref: true, "SetPos", .unknown(8, "Axis"), .float),
        Function(4104, ref: true, "GetAngle", .unknown(8, "Axis")),
        Function(4105, ref: true, "SetAngle", .unknown(8, "Axis"), .float),
        Function(4106, ref: true, "GetStartingPos", .unknown(8, "Axis")),
        Function(4107, ref: true, "GetStartingAngle", .unknown(8, "Axis")),
        Function(4108, "GetSecondsPassed"),
        Function(4109, ref: true, "Activate", .unknown(4, "ObjectReferenceID"), .integer),
        Function(4110, ref: true, "GetActorValue", abbrev: "GetAV", .actorValue, description: "Get an actor value. [player.getav luck]"),
        Function(4111, ref: true, "SetActorValue", abbrev: "SetAV", .actorValue, .float("Amount"), description: "Set an actor value. [player.setav luck, 75]"),
        Function(4112, ref: true, "ModActorValue", abbrev: "ModAV", .actorValue, .float("Amount"), description: "Modify an actor value. [player.modav luck, -10]"),
        Function(4113, ref: true, "SetAtStart"),
        Function(4114, "GetCurrentTime"),
        Function(4115, ref: true, "PlayGroup", .unknown(10, "Animation Group"), .integer("Flags"), description: "IE: PlayGroup SEQNAME 1"),
        Function(4116, ref: true, "LoopGroup", .unknown(10, "Animation Group"), .integer, .integer("Flags")),
        Function(4117, ref: true, "SkipAnim"),
        Function(4118, ref: true, "StartCombat", .actor),
        Function(4119, ref: true, "StopCombat"),
        Function(4120, ref: true, "GetScale"),
        Function(4121, ref: true, "IsMoving", description: "Is the actor moving?"),
        Function(4122, ref: true, "IsTurning", description: "Is the actor turning?"),
        Function(4123, ref: true, "GetLineOfSight", abbrev: "GetLOS", .unknown(4, "ObjectReferenceID")),
        Function(4124, ref: true, "AddSpell", .unknown(7, "Spell Item")),
        Function(4125, ref: true, "RemoveSpell", .unknown(7, "Spell Item")),
        Function(4126, ref: true, "Cast", .unknown(11, "Magic Item"), .unknown(4, "ObjectReferenceID"), .unknown(68, "Source")),
        Function(4127, "GetButtonPressed"),
        Function(4128, ref: true, "GetInSameCell", .unknown(4, "ObjectReferenceID")),
        Function(4129, ref: true, "Enable", .integer),
        Function(4130, ref: true, "Disable", .integer),
        Function(4131, ref: true, "GetDisabled"),
        Function(4132, "MenuMode", .integer),
        Function(4133, ref: true, "PlaceAtMe", .unknown(21, "ObjectID"), .integer("Count"), .integer("Distance"), .integer("Direction")),
        Function(4134, "PlaySound", .unknown(12, "Sound"), .integer, description: "Play a 2D sound. (Optional: 1 to indicate a system sound, 0 otherwise."),
        Function(4135, ref: true, "GetDisease"),
        Function(4136, "FailAllObjectives", .quest, description: "Fail all of a quest's objectives"),
        Function(4137, ref: true, "GetClothingValue"),
        Function(4138, ref: true, "SameFaction", .actor),
        Function(4139, ref: true, "SameRace", .actor),
        Function(4140, ref: true, "SameSex", .actor),
        Function(4141, ref: true, "GetDetected", .actor),
        Function(4142, ref: true, "GetDead"),
        Function(4143, ref: true, "GetItemCount", .unknown(53, "ObjectID")),
        Function(4144, ref: true, "GetGold"),
        Function(4145, ref: true, "GetSleeping"),
        Function(4146, ref: true, "GetTalkedToPC"),
        Function(4147, ref: true, "Say", .topic, .integer, .unknown(25, "Actor Base"), .integer, .integer),
        Function(4148, ref: true, "SayTo", .actor, .topic, .integer, .integer),
        Function(4149, "GetScriptVariable", .unknown(4, "ObjectReferenceID"), .unknown(22, "Variable Name")),
        Function(4150, "StartQuest", .quest),
        Function(4151, "StopQuest", .quest),
        Function(4152, "GetQuestRunning", abbrev: "GetQR", .quest),
        Function(4153, "SetStage", .quest, .unknown(23, "Stage")),
        Function(4154, "GetStage", .quest),
        Function(4155, "GetStageDone", .quest, .unknown(23, "Stage")),
        Function(4156, ref: true, "GetFactionRankDifference", .faction, .actor),
        Function(4157, ref: true, "GetAlarmed"),
        Function(4158, "IsRaining"),
        Function(4159, ref: true, "GetAttacked"),
        Function(4160, ref: true, "GetIsCreature"),
        Function(4161, ref: true, "GetLockLevel"),
        Function(4162, ref: true, "GetShouldAttack", .actor),
        Function(4163, ref: true, "GetInCell", .unknown(9, "Cell")),
        Function(4164, ref: true, "GetIsClass", .unknown(16, "Class")),
        Function(4165, ref: true, "GetIsRace", .unknown(15, "Race")),
        Function(4166, ref: true, "GetIsSex", .unknown(18, "Sex")),
        Function(4167, ref: true, "GetInFaction", .faction),
        Function(4168, ref: true, "GetIsID", .unknown(21, "ObjectID")),
        Function(4169, ref: true, "GetFactionRank", .faction),
        Function(4170, "GetGlobalValue", .unknown(19, "Global")),
        Function(4171, "IsSnowing"),
        Function(4172, "FastTravel", abbrev: "ft", .unknown(4, "TESObjectREFR"), description: "Player Fast Travel to Marker"),
        Function(4173, "GetRandomPercent"),
        Function(4174, "RemoveMusic", .unknown(57, "Music")),
        Function(4175, "GetQuestVariable", .quest, .unknown(22, "Variable Name")),
        Function(4176, ref: true, "GetLevel"),
        Function(4177, ref: true, "IsRotating"),
        Function(4178, ref: true, "RemoveItem", .unknown(53, "ObjectID"), .integer("Count"), .integer("Flag")),
        Function(4179, ref: true, "GetLeveledEncounterValue", .integer),
        Function(4180, "GetDeadCount", .unknown(25, "Actor Base")),
        Function(4181, "AddToMap", abbrev: "ShowMap", .unknown(24, "Map Marker"), .integer),
        Function(4182, ref: true, "StartConversation", .unknown(4, "TESObjectREFR"), .topic, .unknown(4, "TESObjectREFR"), .unknown(4, "TESObjectREFR"), .integer, .integer, description: "Start a conversation [Bob.StartConversation Joe, SecretTopic]"),
        Function(4183, ref: true, "Drop", .unknown(3, "ObjectID"), .integer("Count")),
        Function(4184, "AddTopic", .topic),
        Function(4185, "ShowMessage", .unknown(52, "Message")),
        Function(4186, ref: true, "SetAlert", .integer),
        Function(4187, ref: true, "GetIsAlerted"),
        Function(4188, ref: true, "Look", .unknown(4, "ObjectReferenceID"), .integer),
        Function(4189, ref: true, "StopLook"),
        Function(4190, ref: true, "EvaluatePackage", abbrev: "evp"),
        Function(4191, "SendAssaultAlarm", .actor, .faction),
        Function(4192, "EnablePlayerControls", abbrev: "epc", .integer, .integer, .integer, .integer, .integer, .integer, .integer, .integer, .integer, description: "9 optional (0/1) values. movement|fighting|pov|looking|sneaking|menu|activate|journal|POV Type ex: 1 0 0 1 0 0 0 0 0"),
        Function(4193, "DisablePlayerControls", abbrev: "dpc", .integer, .integer, .integer, .integer, .integer, .integer, .integer, .integer, .integer, description: "9 optional (0/1) values. movement|fighting|pov|looking|sneaking|menu|activate|journal|POV Type ex: 1 0 0 1 0 0 0 0 0"),
        Function(4194, "GetPlayerControlsDisabled", abbrev: "gpc", .integer, .integer, .integer, .integer, .integer, .integer, .integer, .integer, description: "8 optional (0/1) values. movement|fighting|pov|looking|sneaking|menu|activate|journal ex: 1 0 0 1 0 0 0 0"),
        Function(4195, ref: true, "GetHeadingAngle", .unknown(4, "ObjectReferenceID")),
        Function(4196, ref: true, "PickIdle"),
        Function(4197, ref: true, "IsWeaponMagicOut"),
        Function(4198, ref: true, "IsTorchOut"),
        Function(4199, ref: true, "IsShieldOut"),
        Function(4200, ref: true, "CreateDetectionEvent", .unknown(4, "TESObjectREFR"), .integer("Integer") ),
        Function(4201, ref: true, "IsActionRef", .unknown(4, "ObjectReferenceID")),
        Function(4202, ref: true, "IsFacingUp"),
        Function(4203, ref: true, "GetKnockedState"),
        Function(4204, ref: true, "GetWeaponAnimType"),
        Function(4205, ref: true, "IsWeaponSkillType", .actorValue),
        Function(4206, ref: true, "GetCurrentAIPackage"),
        Function(4207, ref: true, "IsWaiting"),
        Function(4208, ref: true, "IsIdlePlaying"),
        Function(4209, "CompleteQuest", .quest),
        Function(4210, ref: true, "Lock", .integer, .integer),
        Function(4211, ref: true, "UnLock", .integer),
        Function(4212, ref: true, "IsIntimidatedbyPlayer"),
        Function(4213, "IsPlayerInRegion", .unknown(82, "Region")),
        Function(4214, ref: true, "GetActorAggroRadiusViolated"),
        Function(4215, ref: true, "GetCrimeKnown", .unknown(28, "Crime Type"), .actor("Criminal"), .actor("Victim")),
        Function(4216, "SetEnemy", .faction, .faction, .integer("Value"), .integer("Value")),
        Function(4217, "SetAlly", .faction, .faction, .integer("Value"), .integer("Value")),
        Function(4218, ref: true, "GetCrime", .actor, .unknown(28, "Crime Type")),
        Function(4219, ref: true, "IsGreetingPlayer"),
        Function(4220, ref: true, "StartMisterSandMan", .actor),
        Function(4221, ref: true, "IsGuard"),
        Function(4222, ref: true, "StartCannibal", .actor),
        Function(4223, ref: true, "HasBeenEaten"),
        Function(4224, ref: true, "GetStaminaPercentage", abbrev: "GetStamina"),
        Function(4225, "GetPCIsClass", .unknown(16, "Class")),
        Function(4226, "GetPCIsRace", .unknown(15, "Race")),
        Function(4227, "GetPCIsSex", .unknown(18, "Sex")),
        Function(4228, "GetPCInFaction", .faction),
        Function(4229, ref: true, "SameFactionAsPC"),
        Function(4230, ref: true, "SameRaceAsPC"),
        Function(4231, ref: true, "SameSexAsPC"),
        Function(4232, ref: true, "GetIsReference", .unknown(4, "ObjectReferenceID")),
        Function(4233, ref: true, "SetFactionRank", .faction, .integer("Value")),
        Function(4234, ref: true, "ModFactionRank", .faction, .integer("Value")),
        Function(4235, ref: true, "KillActor", abbrev: "kill", .actor, .integer, .integer),
        Function(4236, ref: true, "ResurrectActor", abbrev: "resurrect", .integer),
        Function(4237, ref: true, "IsTalking"),
        Function(4238, ref: true, "GetWalkSpeed", abbrev: "GetWalk"),
        Function(4239, ref: true, "GetCurrentAIProcedure"),
        Function(4240, ref: true, "GetTrespassWarningLevel"),
        Function(4241, ref: true, "IsTrespassing"),
        Function(4242, ref: true, "IsInMyOwnedCell"),
        Function(4243, "GetWindSpeed"),
        Function(4244, "GetCurrentWeatherPercent", abbrev: "getweatherpct"),
        Function(4245, "GetIsCurrentWeather", abbrev: "getweather", .unknown(33, "Weather ID")),
        Function(4246, ref: true, "IsContinuingPackagePCNear"),
        Function(4247, ref: true, "SetCrimeFaction", .faction),
        Function(4248, ref: true, "GetIsCrimeFaction", .faction),
        Function(4249, ref: true, "CanHaveFlames"),
        Function(4250, ref: true, "HasFlames"),
        Function(4251, ref: true, "AddFlames"),
        Function(4252, ref: true, "RemoveFlames"),
        Function(4253, ref: true, "GetOpenState"),
        Function(4254, ref: true, "MoveToMarker", abbrev: "MoveTo", .unknown(4, "ObjectReferenceID"), .float, .float, .float),
        Function(4255, ref: true, "GetSitting"),
        Function(4256, ref: true, "GetFurnitureMarkerID"),
        Function(4257, ref: true, "GetIsCurrentPackage", .unknown(29, "Package")),
        Function(4258, ref: true, "IsCurrentFurnitureRef", .unknown(4, "ObjectReferenceID")),
        Function(4259, ref: true, "IsCurrentFurnitureObj", .unknown(20, "Furniture")),
        Function(4260, ref: true, "SetSize", abbrev: "CSize", .float, description: "Shrink/Grow an actor. [player.shrink 0.0 or radius]"),
        Function(4261, ref: true, "RemoveMe", .container),
        Function(4262, ref: true, "DropMe"),
        Function(4263, "GetFactionReaction", .faction, .faction),
        Function(4264, "SetFactionReaction", .faction, .faction, .integer("Value")),
        Function(4265, "ModFactionReaction", .faction, .faction, .integer("Value")),
        Function(4266, "GetDayOfWeek"),
        Function(4267, ref: true, "IgnoreCrime", .integer),
        Function(4268, "GetTalkedToPCParam", .actor),
        Function(4269, ref: true, "RemoveAllItems", .container, .integer("Ownership Added"), .integer("No Message Flag")),
        Function(4270, "WakeUpPC", .integer),
        Function(4271, "IsPCSleeping"),
        Function(4272, "IsPCAMurderer"),
        Function(4273, ref: true, "SetCombatStyle", abbrev: "setcs", .unknown(30, "Combat Style")),
        Function(4274, "PlaySound3D", .unknown(12, "Sound")),
        Function(4275, "SelectPlayerSpell", abbrev: "spspell", .unknown(7, "Spell Item"), .unknown(68, "Casting Source")),
        Function(4276, ref: true, "HasSameEditorLocAsRef", .unknown(4, "TESObjectREFR"), .unknown(59, "Keyword")),
        Function(4277, ref: true, "HasSameEditorLocAsRefAlias", .questAlias, .unknown(59, "Keyword")),
        Function(4278, ref: true, "GetEquipped", .unknown(53, "ObjectID")),
        Function(4279, ref: true, "Wait", .unknown(29, "Package")),
        Function(4280, ref: true, "StopWaiting", .unknown(29, "Package")),
        Function(4281, ref: true, "IsSwimming"),
        Function(4282, "ScriptEffectElapsedSeconds"),
        Function(4283, "SetCellPublicFlag", abbrev: "setpublic", .unknown(9, "Cell"), .integer("Flag"), description: "Set public flag on cell. [setpublic MyCell 1]"),
        Function(4284, "GetPCSleepHours"),
        Function(4285, "SetPCSleepHours", .integer),
        Function(4286, "GetAmountSoldStolen"),
        Function(4287, "ModAmountSoldStolen", .integer),
        Function(4288, "GetIgnoreCrime"),
        Function(4289, "GetPCExpelled", .faction),
        Function(4290, "SetPCExpelled", .faction, .integer("Value")),
        Function(4291, "GetPCFactionMurder", .faction),
        Function(4292, "SetPCFactionMurder", .faction, .integer("Value")),
        Function(4293, "GetPCEnemyofFaction", .faction),
        Function(4294, "SetPCEnemyofFaction", .faction, .integer("Value")),
        Function(4295, "GetPCFactionAttack", .faction),
        Function(4296, "SetPCFactionAttack", .faction, .integer("Value")),
        Function(4297, "StartScene", .scene),
        Function(4298, "StopScene", .scene),
        Function(4299, ref: true, "GetDestroyed"),
        Function(4300, ref: true, "SetDestroyed", .integer),
        Function(4301, ref: true, "GetActionRef", abbrev: "getAR"),
        Function(4302, ref: true, "GetSelf", abbrev: "this"),
        Function(4303, ref: true, "GetContainer"),
        Function(4304, ref: true, "GetForceRun"),
        Function(4305, ref: true, "SetForceRun", .integer),
        Function(4306, ref: true, "GetForceSneak"),
        Function(4307, ref: true, "SetForceSneak", .integer),
        Function(4308, "AdvancePCSkill", abbrev: "AdvSkill", .actorValue, .float("Amount"), description: "Give the player the given amount of skill usage [advskill onehanded 100]"),
        Function(4309, "AdvancePCLevel", abbrev: "AdvLevel"),
        Function(4310, ref: true, "HasMagicEffect", .unknown(31, "Magic Effect")),
        Function(4311, ref: true, "GetDefaultOpen", description: "Returns 1 if this object is open by default."),
        Function(4312, ref: true, "SetDefaultOpen", .integer, description: "A value of 1 will make the object open by default."),
        Function(4313, "ShowClassMenu"),
        Function(4314, "ShowRaceMenu", abbrev: "SetPlayerRace", .unknown(15, "Race"), description: "ShowRaceMenu no parameter will bring up the race menu. SetPlayerRace raceID will change the players race to raceID and reload the players geometry."),
        Function(4315, ref: true, "GetAnimAction", description: "Return the actors current anim action."),
        Function(4316, "ShowNameMenu"),
        Function(4317, ref: true, "SetOpenState", .integer, description: "A value of 1 will make the object open."),
        Function(4318, ref: true, "ResetReference", abbrev: "RecycleActor", .unknown(4, "ObjectReferenceID"), description: "Optional destination reference."),
        Function(4319, ref: true, "IsSpellTarget", .unknown(11, "Magic Item")),
        Function(4320, "GetVATSMode"),
        Function(4321, "GetPersuasionNumber"),
        Function(4322, ref: true, "GetVampireFeed"),
        Function(4323, ref: true, "GetCannibal"),
        Function(4324, "GetIsClassDefault", .unknown(16, "Class")),
        Function(4325, "GetClassDefaultMatch"),
        Function(4326, "GetInCellParam", .unknown(9, "Cell"), .unknown(4, "ObjectReferenceID")),
        Function(4327, "UnusedFunction1"),
        Function(4328, ref: true, "GetCombatTarget"),
        Function(4329, ref: true, "GetPackageTarget"),
        Function(4330, "ShowSpellMaking"),
        Function(4331, "GetVatsTargetHeight"),
        Function(4332, ref: true, "SetGhost", .integer, description: "A value of 1 will make the NPC act as a 'ghost'."),
        Function(4333, ref: true, "GetIsGhost", description: "Returns 1 if the actor is acting as a 'ghost'."),
        Function(4334, ref: true, "EquipItem", abbrev: "EquipObject", .unknown(3, "ObjectID"), .integer("Flag"), .unknown(68, "Hand")),
        Function(4335, ref: true, "UnequipItem", abbrev: "UnEquipObject", .unknown(3, "ObjectID"), .integer("Flag"), .unknown(68, "Hand")),
        Function(4336, ref: true, "SetClass", .unknown(16, "Class")),
        Function(4337, "SetUnconscious", .integer, description: "A value of 1 will be unconscious."),
        Function(4338, ref: true, "GetUnconscious", description: "Returns 1 if is unconscious."),
        Function(4339, "SetRestrained", .integer, description: "A value of 1 will be restrained."),
        Function(4340, ref: true, "GetRestrained", description: "Returns 1 if is restrained."),
        Function(4341, ref: true, "ForceFlee", abbrev: "Flee", .unknown(9, "Cell"), .unknown(4, "ObjectReferenceID"), description: "Forces a actor to flee if destination or cell is passed in uses them"),
        Function(4342, "GetIsUsedItem", .unknown(56, "ObjectID")),
        Function(4343, "GetIsUsedItemType", .unknown(32, "Form Type")),
        Function(4344, "IsScenePlaying", .scene),
        Function(4345, ref: true, "IsInDialogueWithPlayer", description: "True if actor is currently in a dialogue state with player"),
        Function(4346, "GetLocationCleared", .unknown(61, "Location")),
        Function(4347, "SetLocationCleared", .unknown(61, "Location"), .integer),
        Function(4348, ref: true, "ForceRefIntoAlias", .questAlias),
        Function(4349, "EmptyRefAlias", .questAlias),
        Function(4350, ref: true, "GetIsPlayableRace"),
        Function(4351, ref: true, "GetOffersServicesNow"),
        Function(4352, "GetGameSetting", abbrev: "GetGS", .string),
        Function(4353, ref: true, "StopCombatAlarmOnActor", abbrev: "SCAOnActor"),
        Function(4354, ref: true, "HasAssociationType", .actor, .unknown(69, "AssociationType")),
        Function(4355, ref: true, "HasFamilyRelationship", abbrev: "Family", .actor),
        Function(4356, "SetWeather", abbrev: "sw", .unknown(33, "Weather ID"), .integer, description: "Sets the active weather to the specified type"),
        Function(4357, ref: true, "HasParentRelationship", abbrev: "IsParent", .actor),
        Function(4358, ref: true, "IsWarningAbout", .unknown(37, "Form List")),
        Function(4359, ref: true, "IsWeaponOut"),
        Function(4360, ref: true, "HasSpell", .unknown(7, "Spell Item")),
        Function(4361, "IsTimePassing"),
        Function(4362, "IsPleasant"),
        Function(4363, "IsCloudy"),
        Function(4364, "TrapUpdate"),
        Function(4365, "ShowQuestObjectives", abbrev: "SQO", .quest, description: "Shows the list of current quest objectives"),
        Function(4366, ref: true, "ForceActorValue", abbrev: "ForceAV", .actorValue, .float("Amount"), description: "Does modav XXX (value - getav XXX). [player.forceav luck 25]"),
        Function(4367, "IncrementPCSkill", abbrev: "IncPCS", .actorValue, description: "Increase the player's skill by one point. [IncrementSkill onehanded]"),
        Function(4368, ref: true, "DoTrap", .unknown(4, "Trap"), .float("Damage"), .float("Lev. Damage"), .float("Pushback"), .float("Death Pushback"), .float("Min. Velocity"), .integer("Continuous"), .float("Stagger")),
        Function(4369, "EnableFastTravel", abbrev: "EnableFast", .integer),
        Function(4370, ref: true, "IsSmallBump"),
        Function(4371, ref: true, "GetParentRef"),
        Function(4372, "PlayBink", .string, .integer, .integer, .integer, .integer),
        Function(4373, ref: true, "GetBaseActorValue", abbrev: "GetBaseAV", .actorValue, description: "Get a base actor value. [player.getbaseav luck]"),
        Function(4374, ref: true, "IsOwner", .unknown(35, "Owner"), description: "get the ownership of the ref"),
        Function(4375, ref: true, "SetOwnership", .unknown(35, "Owner")),
        Function(4376, ref: true, "IsCellOwner", .unknown(9, "Cell"), .unknown(35, "Owner"), description: "get the ownership of the ref"),
        Function(4377, "SetCellOwnership", .unknown(9, "Cell"), .unknown(35, "Owner")),
        Function(4378, ref: true, "IsHorseStolen"),
        Function(4379, "SetCellFullName", .unknown(9, "Cell"), .unknown(52, "Message")),
        Function(4380, ref: true, "SetActorFullName", .unknown(52, "Message")),
        Function(4381, ref: true, "IsLeftUp"),
        Function(4382, ref: true, "IsSneaking"),
        Function(4383, ref: true, "IsRunning"),
        Function(4384, ref: true, "GetFriendHit"),
        Function(4385, ref: true, "IsInCombat", .integer),
        Function(4386, ref: true, "SetPackDuration", abbrev: "SPDur", .float),
        Function(4387, ref: true, "PlayMagicShaderVisuals", abbrev: "PMS", .unknown(36, "Effect Shader ID"), .float("Time")),
        Function(4388, ref: true, "PlayMagicEffectVisuals", abbrev: "PME", .unknown(31, "Magic Effect"), .float("Time")),
        Function(4389, ref: true, "StopMagicShaderVisuals", abbrev: "SMS", .unknown(36, "Effect Shader ID")),
        Function(4390, ref: true, "StopMagicEffectVisuals", abbrev: "SME", .unknown(31, "Magic Effect")),
        Function(4391, "ResetInterior", .unknown(9, "Cell")),
        Function(4392, ref: true, "IsAnimPlaying", .unknown(10, "Animation Group")),
        Function(4393, ref: true, "SetActorAlpha", abbrev: "SAA", .float, .integer("Int")),
        Function(4394, ref: true, "EnableLinkedPathPoints"),
        Function(4395, ref: true, "DisableLinkedPathPoints"),
        Function(4396, ref: true, "IsInInterior"),
        Function(4397, "ForceWeather", abbrev: "fw", .unknown(33, "Weather ID"), .integer, description: "Forces the active weather to the specified type, without transition."),
        Function(4398, ref: true, "ToggleActorsAI"),
        Function(4399, ref: true, "IsActorsAIOff"),
        Function(4400, ref: true, "IsWaterObject", description: "Water condition used for drinking animation."),
        Function(4401, ref: true, "GetPlayerAction"),
        Function(4402, ref: true, "IsActorUsingATorch"),
        Function(4403, ref: true, "SetLevel", .integer, .integer, .integer, .integer),
        Function(4404, ref: true, "ResetFallDamageTimer"),
        Function(4405, "IsXBox"),
        Function(4406, ref: true, "GetInWorldspace", .unknown(27, "WorldSpace")),
        Function(4407, "ModPCMiscStat", abbrev: "ModPCMS", .unknown(41, "Miscellaneous Stat"), .integer),
        Function(4408, "GetPCMiscStat", abbrev: "GetPCMS", .unknown(41, "Miscellaneous Stat")),
        Function(4409, ref: true, "GetPairedAnimation", abbrev: "GPA", description: "See if this reference is currently playing a paired animation."),
        Function(4410, ref: true, "IsActorAVictim"),
        Function(4411, "GetTotalPersuasionNumber"),
        Function(4412, ref: true, "SetScale", .float, description: "Set the scale of an object"),
        Function(4413, ref: true, "ModScale", .float, description: "Modify the scale of an object"),
        Function(4414, "GetIdleDoneOnce"),
        Function(4415, "KillAllActors", abbrev: "killall", .actor),
        Function(4416, ref: true, "GetNoRumors"),
        Function(4417, ref: true, "SetNoRumors", .integer),
        Function(4418, ref: true, "Dispel", .unknown(11, "Magic Item")),
        Function(4419, ref: true, "GetCombatState"),
        Function(4420, "TriggerHitShader", abbrev: "ths", .float),
        Function(4421, ref: true, "GetWithinPackageLocation", .unknown(78, "PackageData (Location)")),
        Function(4422, "Reset3DState"),
        Function(4423, ref: true, "IsRidingHorse"),
        Function(4424, ref: true, "DispelAllSpells"),
        Function(4425, ref: true, "IsFleeing"),
        Function(4426, "AddAchievement", .integer),
        Function(4427, ref: true, "DuplicateAllItems", .container, .integer("Ownership Added")),
        Function(4428, ref: true, "IsInDangerousWater"),
        Function(4429, "EssentialDeathReload", .string),
        Function(4430, "SetShowQuestItems", .integer),
        Function(4431, ref: true, "DuplicateNPCStats", .actor),
        Function(4432, ref: true, "ResetHealth"),
        Function(4433, ref: true, "SetIgnoreFriendlyHits", abbrev: "sifh", .integer, description: "Set whether an actor should ignore friendly hits (0-no, 1-yes)"),
        Function(4434, ref: true, "GetIgnoreFriendlyHits", abbrev: "gifh", description: "See if an actor is ignoring friendly hits"),
        Function(4435, ref: true, "IsPlayersLastRiddenHorse"),
        Function(4436, ref: true, "SetActorRefraction", abbrev: "sar", .float),
        Function(4437, ref: true, "SetItemValue", .integer),
        Function(4438, "SetRigidBodyMass", .float),
        Function(4439, ref: true, "ShowViewerStrings", abbrev: "svs"),
        Function(4440, "ReleaseWeatherOverride", abbrev: "rwo"),
        Function(4441, "SetAllReachable", .integer),
        Function(4442, "SetAllVisible", .integer),
        Function(4443, "SetNoAvoidance", .integer),
        Function(4444, ref: true, "SendTrespassAlarm", .actor),
        Function(4445, "SetSceneIsComplex", .integer),
        Function(4446, "Autosave"),
        Function(4447, "StartMasterFileSeekData"),
        Function(4448, "DumpMasterFileSeekData"),
        Function(4449, ref: true, "IsActor"),
        Function(4450, ref: true, "IsEssential"),
        Function(4451, ref: true, "PreloadMagicEffect", .unknown(31, "Magic Effect")),
        Function(4452, "ShowDialogSubtitles", .integer),
        Function(4453, ref: true, "SetPlayerResistingArrest"),
        Function(4454, "IsPlayerMovingIntoNewSpace"),
        Function(4455, ref: true, "GetInCurrentLoc", .unknown(61, "Location")),
        Function(4456, ref: true, "GetInCurrentLocAlias", .questAlias),
        Function(4457, ref: true, "GetTimeDead"),
        Function(4458, ref: true, "HasLinkedRef", .unknown(59, "Keyword")),
        Function(4459, ref: true, "GetLinkedRef", .unknown(59, "Keyword")),
        Function(4460, ref: true, "DamageObject", abbrev: "do", .float),
        Function(4461, ref: true, "IsChild"),
        Function(4462, "GetStolenItemValueNoCrime", .faction),
        Function(4463, "GetLastPlayerAction"),
        Function(4464, "IsPlayerActionActive", .integer),
        Function(4465, ref: true, "SetTalkingActivatorActor", .actor),
        Function(4466, ref: true, "IsTalkingActivatorActor", .actor),
        Function(4467, ref: true, "ShowBarterMenu", abbrev: "sbm", .integer),
        Function(4468, ref: true, "IsInList", .unknown(37, "Form List")),
        Function(4469, "GetStolenItemValue", .faction),
        Function(4470, ref: true, "AddPerk", .unknown(39, "Perk")),
        Function(4471, ref: true, "GetCrimeGoldViolent", abbrev: "getviolent", .faction),
        Function(4472, ref: true, "GetCrimeGoldNonviolent", abbrev: "getnonviolent", .faction),
        Function(4473, "ShowRepairMenu", abbrev: "srm"),
        Function(4474, ref: true, "HasShout", .unknown(64, "Shout")),
        Function(4475, "AddNote", abbrev: "AN", .unknown(40, "Note")),
        Function(4476, "RemoveNote", abbrev: "RN", .unknown(40, "Note")),
        Function(4477, "GetHasNote", abbrev: "GetN", .unknown(40, "Note")),
        Function(4478, ref: true, "AddToFaction", abbrev: "Addfac", .faction, .integer("Value")),
        Function(4479, ref: true, "RemoveFromFaction", abbrev: "Removefac", .faction),
        Function(4480, ref: true, "DamageActorValue", abbrev: "DamageAV", .actorValue, .float("Amount"), description: "Damage an actor value."),
        Function(4481, ref: true, "RestoreActorValue", abbrev: "RestoreAV", .actorValue, .float("Amount"), description: "Restore an actor value."),
        Function(4482, "TriggerHUDShudder", abbrev: "hudsh", .float, .float, .float, .float, description: "Trigger shudder effect on HUD.  Params=Intensity/Duration."),
        Function(4483, "GetObjectiveFailed", .quest, .integer),
        Function(4484, "SetObjectiveFailed", .quest, .integer, .integer("State")),
        Function(4485, "SetGlobalTimeMultiplier", abbrev: "sgtm", .float),
        Function(4486, ref: true, "GetHitLocation", description: "What BGSBodyPart::LIMB_ENUM was hit. -1 = none, 0 = torso, ..."),
        Function(4487, "IsPC1stPerson", abbrev: "pc1st", description: "Is the player playing in 1st person mode?"),
        Function(4488, "PurgeCellBuffers", abbrev: "pcb", description: "Forcibly unloads all unattached cells in cell buffers."),
        Function(4489, ref: true, "PushActorAway", .unknown(4, "ObjectReferenceID"), .integer),
        Function(4490, ref: true, "SetActorsAI", .integer),
        Function(4491, ref: true, "ClearOwnership"),
        Function(4492, ref: true, "GetCauseofDeath", description: "What killed the actor"),
        Function(4493, ref: true, "IsLimbGone", .integer, description: "Is BGSBodyPart::LIMB_ENUM been dismembered"),
        Function(4494, ref: true, "IsWeaponInList", .unknown(37, "Form List"), description: "Is the current weapon in the form list"),
        Function(4495, ref: true, "PlayIdle", .string, description: "Play this idle on the current actor."),
        Function(4496, "ApplyImageSpaceModifier", abbrev: "imod", .unknown(42, "Imagespace Modifier ID"), .float, description: "Adds an imagespace modifier to the active list"),
        Function(4497, "RemoveImageSpaceModifier", abbrev: "rimod", .unknown(42, "Imagespace Modifier ID"), .float, description: "Removes an imagespace modifier from the active list"),
        Function(4498, ref: true, "IsBribedbyPlayer"),
        Function(4499, ref: true, "GetRelationshipRank", .actor),
        Function(4500, ref: true, "SetRelationshipRank", .actor, .integer("Value")),
        Function(4501, "SetCellImageSpace", .unknown(9, "Cell"), .unknown(43, "ImageSpace")),
        Function(4502, "ShowChargenMenu", abbrev: "scgm"),
        Function(4503, "GetVATSValue", .integer, .integer),
        Function(4504, ref: true, "IsKiller", .actor),
        Function(4505, ref: true, "IsKillerObject", .unknown(37, "Form List")),
        Function(4506, "GetFactionCombatReaction", .faction, .faction),
        Function(4507, ref: true, "UseWeapon", .unknown(21, "Weapon"), .unknown(4, "Location"), .unknown(4, "Target"), .integer("NumAttacks"), .integer("CrouchToReload"), .integer("HoldFire"), .integer("AlwaysHit"), .integer("DoNoDamage"), .unknown(4, "TargetLocation")),
        Function(4508, ref: true, "EvaluateSpellConditions", abbrev: "esc"),
        Function(4509, "ToggleMotionBlur", abbrev: "tmb", description: "Toggle Motion Blur for the selected reference"),
        Function(4510, ref: true, "Exists", .unknown(4, "ObjectReferenceID")),
        Function(4511, ref: true, "GetGroupMemberCount"),
        Function(4512, ref: true, "GetGroupTargetCount"),
        Function(4513, "SetObjectiveCompleted", .quest, .integer, .integer("State"), description: "Set objective completion status: 0-Off, 1-On"),
        Function(4514, "SetObjectiveDisplayed", .quest, .integer, .integer("State"), description: "Set objective displayed status: 0-Off, 1-On"),
        Function(4515, "GetObjectiveCompleted", .quest, .integer, description: "Get objective completion status: 0-Off, 1-On"),
        Function(4516, "GetObjectiveDisplayed", .quest, .integer, description: "Get objective displayed status: 0-Off, 1-On"),
        Function(4517, "SetImageSpace", .unknown(43, "ImageSpace")),
        Function(4518, "PipboyRadio", abbrev: "prad", .string, .unknown(4, "ObjectReferenceID"), description: "Control the Pipboy radio. Enable, Disable, Tune"),
        Function(4519, ref: true, "RemovePerk", .unknown(39, "Perk")),
        Function(4520, ref: true, "DisableAllActors", abbrev: "DisAA"),
        Function(4521, ref: true, "GetIsFormType", .string),
        Function(4522, ref: true, "GetIsVoiceType", .unknown(49, "VoiceType")),
        Function(4523, ref: true, "GetPlantedExplosive"),
        Function(4524, "CompleteAllObjectives", .quest, description: "Complete all of a quest's objectives"),
        Function(4525, ref: true, "IsScenePackageRunning"),
        Function(4526, ref: true, "GetHealthPercentage"),
        Function(4527, "SetAudioMultithreading", abbrev: "SAM", .integer),
        Function(4528, ref: true, "GetIsObjectType", .unknown(32, "Form Type")),
        Function(4529, "ShowChargenMenuParams", abbrev: "scgmp", .integer, .integer, .integer),
        Function(4530, ref: true, "GetDialogueEmotion"),
        Function(4531, ref: true, "GetDialogueEmotionValue"),
        Function(4532, "ExitGame", abbrev: "exit"),
        Function(4533, ref: true, "GetIsCreatureType", .integer),
        Function(4534, "PlayerCreatePotion", .unknown(31, "Magic Effect"), .unknown(31, "Magic Effect"), .unknown(31, "Magic Effect")),
        Function(4535, "PlayerEnchantObject", .unknown(21, "Object"), .unknown(31, "Magic Effect"), .unknown(31, "Magic Effect")),
        Function(4536, "ShowWarning", .string),
        Function(4537, ref: true, "EnterTrigger", .unknown(4, "ObjectReferenceID")),
        Function(4538, ref: true, "MarkForDelete"),
        Function(4539, "SetPlayerAIDriven", .integer),
        Function(4540, ref: true, "GetInCurrentLocFormList", .unknown(37, "Form List")),
        Function(4541, ref: true, "GetInZone", .unknown(50, "EncounterZone")),
        Function(4542, ref: true, "GetVelocity", .unknown(8, "Axis"), description: "Gets Velocity on a reference"),
        Function(4543, ref: true, "GetGraphVariableFloat", .string),
        Function(4544, ref: true, "HasPerk", .unknown(39, "Perk")),
        Function(4545, ref: true, "GetFactionRelation", .actor),
        Function(4546, ref: true, "IsLastIdlePlayed", .unknown(51, "Idle Form")),
        Function(4547, "SetNPCRadio", abbrev: "snr", .integer, .unknown(4, "ObjectReferenceID"), description: "Enable/Disable NPC radio playback: 0-Off, 1-On "),
        Function(4548, ref: true, "SetPlayerTeammate", .integer),
        Function(4549, ref: true, "GetPlayerTeammate"),
        Function(4550, "GetPlayerTeammateCount"),
        Function(4551, ref: true, "OpenActorContainer", .integer),
        Function(4552, "ClearFactionPlayerEnemyFlag", .faction),
        Function(4553, ref: true, "ClearActorsFactionsPlayerEnemyFlag"),
        Function(4554, ref: true, "GetActorCrimePlayerEnemy"),
        Function(4555, ref: true, "GetCrimeGold", .faction),
        Function(4556, ref: true, "SetCrimeGold", .integer("Integer") , .faction),
        Function(4557, ref: true, "ModCrimeGold", .integer("Integer") , .integer, .faction),
        Function(4558, "GetPlayerGrabbedRef"),
        Function(4559, "IsPlayerGrabbedRef", .unknown(4, "TESObjectREFR")),
        Function(4560, "PlaceLeveledActorAtMe", .unknown(21, "ObjectID"), .integer("LevelModifier"), .unknown(50, "ForcedZone")),
        Function(4561, ref: true, "GetKeywordItemCount", .unknown(59, "Keyword")),
        Function(4562, "ShowLockpickMenu", abbrev: "slpm", .integer),
        Function(4563, ref: true, "GetBroadcastState"),
        Function(4564, ref: true, "SetBroadcastState", .integer),
        Function(4565, ref: true, "StartRadioConversation", .topic),
        Function(4566, ref: true, "GetDestructionStage"),
        Function(4567, ref: true, "ClearDestruction"),
        Function(4568, ref: true, "CastImmediateOnSelf", abbrev: "cios", .unknown(11, "Magic Item")),
        Function(4569, ref: true, "GetIsAlignment", .unknown(54, "Alignment")),
        Function(4570, "ResetQuest", .quest),
        Function(4571, "SetQuestDelay", .quest, .float),
        Function(4572, ref: true, "IsProtected"),
        Function(4573, ref: true, "GetThreatRatio", .actor),
        Function(4574, ref: true, "MatchFaceGeometry", .actor, .integer("Value")),
        Function(4575, ref: true, "GetIsUsedItemEquipType", .unknown(55, "EquipType")),
        Function(4576, "GetPlayerName"),
        Function(4577, ref: true, "FireWeapon", .unknown(21, "Weapon")),
        Function(4578, ref: true, "PayCrimeGold", .integer, .integer, .faction),
        Function(4579, ref: true, "UnusedFunction2", .float),
        Function(4580, ref: true, "MatchRace", .actor),
        Function(4581, "SetPCYoung", .integer),
        Function(4582, "SexChange", .unknown(18, "Sex"), .integer),
        Function(4583, ref: true, "IsCarryable"),
        Function(4584, ref: true, "GetConcussed"),
        Function(4585, "SetZoneRespawns", .unknown(50, "EncounterZone"), .integer),
        Function(4586, ref: true, "SetVATSTarget", .integer),
        Function(4587, ref: true, "GetMapMarkerVisible"),
        Function(4588, ref: true, "ResetInventory"),
        Function(4589, "PlayerKnows", .unknown(81, "Knowable Form")),
        Function(4590, ref: true, "GetPermanentActorValue", abbrev: "GetPermAV", .actorValue, description: "Get an actor value ignoring temporary modifiers. [player.getav luck]"),
        Function(4591, ref: true, "GetKillingBlowLimb", description: "Which BGSBodyPart::LIMB_ENUM received the killing blow"),
        Function(4592, ref: true, "GoToJail", .faction, .integer, .integer),
        Function(4593, ref: true, "CanPayCrimeGold", .faction),
        Function(4594, "ServeTime"),
        Function(4595, ref: true, "GetDaysInJail"),
        Function(4596, "EPAlchemyGetMakingPoison"),
        Function(4597, "EPAlchemyEffectHasKeyword", .unknown(59, "Keyword")),
        Function(4598, "ShowAllMapMarkers", abbrev: "tmm", .integer, .integer, .integer, description: "Shows/hides map markers (1 shows, 0 hides)(1 travel(default), 0 no travel)(1 all, 0 all but hidden(default))."),
        Function(4599, ref: true, "GetAllowWorldInteractions"),
        Function(4600, ref: true, "ResetAI"),
        Function(4601, "SetRumble", .float, .float, .float, description: "Creates rumble in the controller (left motor) (right motor) (duration)"),
        Function(4602, "SetNoActivationSound", .unknown(12, "Sound"), description: "Set the sound to play when activation fails (Sound)"),
        Function(4603, "ClearNoActivationSound", description: "Clear the activation failure sound"),
        Function(4604, ref: true, "GetLastHitCritical"),
        Function(4605, "AddMusic", .unknown(57, "Music")),
        Function(4606, "UnusedFunction3"),
        Function(4607, ref: true, "UnusedFunction4"),
        Function(4608, "SetPCToddler", .integer),
        Function(4609, ref: true, "IsCombatTarget", .actor),
        Function(4610, "TriggerScreenBlood", abbrev: "tsb", .integer, description: "Trigger screen blood"),
        Function(4611, ref: true, "GetVATSRightAreaFree", .unknown(4, "TESObjectREFR")),
        Function(4612, ref: true, "GetVATSLeftAreaFree", .unknown(4, "TESObjectREFR")),
        Function(4613, ref: true, "GetVATSBackAreaFree", .unknown(4, "TESObjectREFR")),
        Function(4614, ref: true, "GetVATSFrontAreaFree", .unknown(4, "TESObjectREFR")),
        Function(4615, ref: true, "GetIsLockBroken"),
        Function(4616, "IsPS3"),
        Function(4617, "IsWin32"),
        Function(4618, ref: true, "GetVATSRightTargetVisible", .unknown(4, "TESObjectREFR")),
        Function(4619, ref: true, "GetVATSLeftTargetVisible", .unknown(4, "TESObjectREFR")),
        Function(4620, ref: true, "GetVATSBackTargetVisible", .unknown(4, "TESObjectREFR")),
        Function(4621, ref: true, "GetVATSFrontTargetVisible", .unknown(4, "TESObjectREFR")),
        Function(4622, ref: true, "AttachAshPile", .integer),
        Function(4623, ref: true, "SetCriticalStage", .unknown(58, "CriticalStage")),
        Function(4624, ref: true, "IsInCriticalStage", .unknown(58, "CriticalStage")),
        Function(4625, ref: true, "RemoveFromAllFactions"),
        Function(4626, "GetXPForNextLevel"),
        Function(4627, "ShowLockpickMenuDebug", abbrev: "slpmd", .integer),
        Function(4628, "ForceSave"),
        Function(4629, "GetInfamy", .faction),
        Function(4630, "GetInfamyViolent", .faction),
        Function(4631, "GetInfamyNonViolent", .faction),
        Function(4632, ref: true, "UnusedFunction5"),
        Function(4633, "Sin", .float, .integer("Int")),
        Function(4634, "Cos", .float, .integer("Int")),
        Function(4635, "Tan", .float, .integer("Int")),
        Function(4636, "Sqrt", .float),
        Function(4637, "Log", .float, .float),
        Function(4638, "Abs", .float),
        Function(4639, "GetQuestCompleted", abbrev: "GetQC", .quest),
        Function(4640, ref: true, "UnusedFunction6"),
        Function(4641, "PipBoyRadioOff"),
        Function(4642, "AutoDisplayObjectives", .integer),
        Function(4643, "IsGoreDisabled"),
        Function(4644, "FadeSFX", abbrev: "FSFX", .float),
        Function(4645, ref: true, "SetMinimalUse", .integer),
        Function(4646, "IsSceneActionComplete", .scene, .integer),
        Function(4647, "ShowQuestStages", abbrev: "SQS", .quest),
        Function(4648, ref: true, "GetSpellUsageNum", .unknown(11, "Magic Item")),
        Function(4649, "ForceRadioStationUpdate", abbrev: "FRSU"),
        Function(4650, "GetActorsInHigh"),
        Function(4651, "HasLoaded3D"),
        Function(4652, "DisableAllMines"),
        Function(4653, "SetLastExtDoorActivated", .unknown(4, "ObjectReferenceID")),
        Function(4654, "KillQuestUpdates", abbrev: "KQU"),
        Function(4655, "IsImageSpaceActive", .unknown(42, "Imagespace Modifier ID")),
        Function(4656, ref: true, "HasKeyword", .unknown(59, "Keyword")),
        Function(4657, ref: true, "HasRefType", .unknown(60, "RefType")),
        Function(4658, ref: true, "LocationHasKeyword", .unknown(59, "Keyword")),
        Function(4659, ref: true, "LocationHasRefType", .unknown(60, "RefType")),
        Function(4660, "CreateEvent", .unknown(59, "Keyword"), .unknown(61, "Location"), .unknown(4, "Ref 1"), .unknown(4, "Ref 2"), .integer("Value 1"), .integer("Value 2")),
        Function(4661, ref: true, "GetIsEditorLocation", .unknown(61, "Location")),
        Function(4662, ref: true, "GetIsAliasRef", .questAlias),
        Function(4663, ref: true, "GetIsEditorLocAlias", .questAlias),
        Function(4664, ref: true, "IsSprinting"),
        Function(4665, ref: true, "IsBlocking"),
        Function(4666, ref: true, "HasEquippedSpell", abbrev: "hasspell", .unknown(68, "Casting Source")),
        Function(4667, ref: true, "GetCurrentCastingType", abbrev: "getcasting", .unknown(68, "Casting Source")),
        Function(4668, ref: true, "GetCurrentDeliveryType", abbrev: "getdelivery", .unknown(68, "Casting Source")),
        Function(4669, ref: true, "EquipSpell", .unknown(7, "Spell Item"), .unknown(68, "Casting Source")),
        Function(4670, ref: true, "GetAttackState", description: "0 = None, 1 = Draw, 2 = Swing, 3 = Hit, 4 = Next Attack, 5 = Follow Through, 6 = Bash"),
        Function(4671, "GetAliasedRef", .questAlias),
        Function(4672, "GetEventData", .unknown(46, "Event Function"), .unknown(47, "Event Member"), .unknown(48, "Data")),
        Function(4673, ref: true, "IsCloserToAThanB", .unknown(4, "TESObjectREFR"), .unknown(4, "TESObjectREFR")),
        Function(4674, ref: true, "EquipShout", .unknown(64, "Shout")),
        Function(4675, ref: true, "GetEquippedShout", .unknown(64, "Shout")),
        Function(4676, ref: true, "IsBleedingOut"),
        Function(4677, "UnlockWord", .unknown(65, "Word Of Power")),
        Function(4678, "TeachWord", .unknown(65, "Word Of Power")),
        Function(4679, ref: true, "AddToContainer", .unknown(4, "TESObjectREFR"), .integer("Flag")),
        Function(4680, ref: true, "GetRelativeAngle", .unknown(4, "ObjectReferenceID"), .unknown(8, "Axis")),
        Function(4681, ref: true, "SendAnimEvent", abbrev: "sae", .string, description: "Send an event to the animation graph."),
        Function(4682, ref: true, "Shout", .unknown(64, "Shout"), .integer, .unknown(4, "ObjectReferenceID")),
        Function(4683, ref: true, "AddShout", .unknown(64, "Shout")),
        Function(4684, ref: true, "RemoveShout", .unknown(64, "Shout")),
        Function(4685, ref: true, "GetMovementDirection"),
        Function(4686, ref: true, "IsInScene"),
        Function(4687, "GetRefTypeDeadCount", .unknown(61, "Location"), .unknown(60, "RefType")),
        Function(4688, "GetRefTypeAliveCount", .unknown(61, "Location"), .unknown(60, "RefType")),
        Function(4689, ref: true, "ApplyHavokImpulse", .float, .float, .float, .float),
        Function(4690, ref: true, "GetIsFlying"),
        Function(4691, ref: true, "IsCurrentSpell", .unknown(7, "Spell Item"), .unknown(68, "Casting Source")),
        Function(4692, ref: true, "SpellHasKeyword", .unknown(68, "Casting Source"), .unknown(59, "Keyword")),
        Function(4693, ref: true, "GetEquippedItemType", .unknown(68, "Casting Source")),
        Function(4694, "GetLocationAliasCleared", .questAlias),
        Function(4695, "SetLocationAliasCleared", .questAlias),
        Function(4696, "GetLocAliasRefTypeDeadCount", .questAlias, .unknown(60, "RefType")),
        Function(4697, "GetLocAliasRefTypeAliveCount", .questAlias, .unknown(60, "RefType")),
        Function(4698, ref: true, "IsWardState", .unknown(70, "Ward State")),
        Function(4699, ref: true, "IsInSameCurrentLocAsRef", .unknown(4, "TESObjectREFR"), .unknown(59, "Keyword")),
        Function(4700, ref: true, "IsInSameCurrentLocAsRefAlias", .questAlias, .unknown(59, "Keyword")),
        Function(4701, "LocAliasIsLocation", .questAlias, .unknown(61, "Location")),
        Function(4702, "GetKeywordDataForLocation", .unknown(61, "Location"), .unknown(59, "Keyword")),
        Function(4703, "SetKeywordDataForLocation", .unknown(61, "Location"), .unknown(59, "Keyword"), .float("Value")),
        Function(4704, "GetKeywordDataForAlias", .questAlias, .unknown(59, "Keyword")),
        Function(4705, "SetKeywordDataForAlias", .questAlias, .unknown(59, "Keyword"), .float("Value")),
        Function(4706, "LocAliasHasKeyword", .questAlias, .unknown(59, "Keyword")),
        Function(4707, ref: true, "IsNullPackageData", .unknown(71, "PackageData (Possibly Null)")),
        Function(4708, ref: true, "GetNumericPackageData", .unknown(72, "PackageData (Numeric)")),
        Function(4709, ref: true, "IsFurnitureAnimType", .unknown(73, "Furniture Anim Type")),
        Function(4710, ref: true, "IsFurnitureEntryType", .unknown(74, "Furniture Entry Type")),
        Function(4711, ref: true, "GetHighestRelationshipRank"),
        Function(4712, ref: true, "GetLowestRelationshipRank"),
        Function(4713, ref: true, "HasAssociationTypeAny", .unknown(69, "AssociationType")),
        Function(4714, ref: true, "HasFamilyRelationshipAny"),
        Function(4715, ref: true, "GetPathingTargetOffset", .unknown(8, "Axis")),
        Function(4716, ref: true, "GetPathingTargetAngleOffset", .unknown(8, "Axis")),
        Function(4717, ref: true, "GetPathingTargetSpeed"),
        Function(4718, ref: true, "GetPathingTargetSpeedAngle", .unknown(8, "Axis")),
        Function(4719, ref: true, "GetMovementSpeed"),
        Function(4720, ref: true, "GetInContainer", .unknown(4, "TESObjectREFR")),
        Function(4721, "IsLocationLoaded", .unknown(61, "Location")),
        Function(4722, "IsLocAliasLoaded", .questAlias),
        Function(4723, ref: true, "IsDualCasting"),
        Function(4724, ref: true, "DualCast", .unknown(11, "Magic Item"), .unknown(4, "ObjectReferenceID")),
        Function(4725, "GetVMQuestVariable", .quest, .variable),
        Function(4726, "GetVMScriptVariable", .unknown(4, "ObjectReferenceID"), .variable),
        Function(4727, ref: true, "IsEnteringInteractionQuick"),
        Function(4728, ref: true, "IsCasting"),
        Function(4729, ref: true, "GetFlyingState"),
        Function(4730, ref: true, "SetFavorState", .integer),
        Function(4731, ref: true, "IsInFavorState"),
        Function(4732, ref: true, "HasTwoHandedWeaponEquipped"),
        Function(4733, ref: true, "IsExitingInstant"),
        Function(4734, ref: true, "IsInFriendStatewithPlayer"),
        Function(4735, ref: true, "GetWithinDistance", .unknown(4, "ObjectReferenceID"), .float),
        Function(4736, ref: true, "GetActorValuePercent", .actorValue),
        Function(4737, ref: true, "IsUnique"),
        Function(4738, ref: true, "GetLastBumpDirection"),
        Function(4739, "CameraShake", .float, .float),
        Function(4740, ref: true, "IsInFurnitureState", .unknown(73, "Furniture Anim Type")),
        Function(4741, ref: true, "GetIsInjured"),
        Function(4742, ref: true, "GetIsCrashLandRequest"),
        Function(4743, ref: true, "GetIsHastyLandRequest"),
        Function(4744, "UpdateQuestInstanceGlobal", .quest, .unknown(19, "Global")),
        Function(4745, ref: true, "SetAllowFlying", .integer),
        Function(4746, ref: true, "IsLinkedTo", .unknown(4, "TESObjectREFR"), .unknown(59, "Keyword")),
        Function(4747, ref: true, "GetKeywordDataForCurrentLocation", .unknown(59, "Keyword")),
        Function(4748, ref: true, "GetInSharedCrimeFaction", .unknown(4, "TESObjectREFR")),
        Function(4749, ref: true, "GetBribeAmount"),
        Function(4750, ref: true, "GetBribeSuccess"),
        Function(4751, ref: true, "GetIntimidateSuccess"),
        Function(4752, ref: true, "GetArrestedState"),
        Function(4753, ref: true, "GetArrestingActor"),
        Function(4754, ref: true, "ClearArrestState"),
        Function(4755, "EPTemperingItemIsEnchanted"),
        Function(4756, "EPTemperingItemHasKeyword", .unknown(59, "Keyword")),
        Function(4757, ref: true, "GetReceivedGiftValue"),
        Function(4758, ref: true, "GetGiftGivenValue"),
        Function(4759, "ForceLocIntoAlias", .unknown(61, "Location"), .questAlias),
        Function(4760, ref: true, "GetReplacedItemType", .unknown(68, "Casting Source")),
        Function(4761, ref: true, "SetHorseActor", .unknown(4, "TESObjectREFR")),
        Function(4762, ref: true, "PlayReferenceEffect", abbrev: "pre", .unknown(77, "Reference Effect"), .float("Time"), .unknown(4, "Aim-at target")),
        Function(4763, ref: true, "StopReferenceEffect", abbrev: "sre", .unknown(77, "Reference Effect")),
        Function(4764, "PlayShaderParticleGeometry", abbrev: "pspg", .unknown(62, "Form"), .float),
        Function(4765, "StopShaderParticleGeometry", abbrev: "sspg", .unknown(62, "Form"), .float),
        Function(4766, "ApplyImageSpaceModifierCrossFade", abbrev: "imodcf", .unknown(42, "Imagespace Modifier ID"), .float, description: "Adds a crossfade imagespace modifier to the active list"),
        Function(4767, "RemoveImageSpaceModifierCrossFade", abbrev: "rimodcf", .float, description: "Remove a crossfade imagespace modifier from the active list"),
        Function(4768, ref: true, "IsAttacking"),
        Function(4769, ref: true, "IsPowerAttacking"),
        Function(4770, ref: true, "IsLastHostileActor"),
        Function(4771, ref: true, "GetGraphVariableInt", .string),
        Function(4772, ref: true, "GetCurrentShoutVariation"),
        Function(4773, ref: true, "PlayImpactEffect", abbrev: "pie", .string, .string, .float, .float, .float, .float, .integer("Int"), .integer("Int")),
        Function(4774, ref: true, "ShouldAttackKill", .actor),
        Function(4775, ref: true, "SendStealAlarm", abbrev: "steal", .actor),
        Function(4776, ref: true, "GetActivationHeight"),
        Function(4777, "EPModSkillUsage_IsAdvanceSkill", .actorValue),
        Function(4778, ref: true, "WornHasKeyword", .unknown(59, "Keyword")),
        Function(4779, ref: true, "GetPathingCurrentSpeed"),
        Function(4780, ref: true, "GetPathingCurrentSpeedAngle", .unknown(8, "Axis")),
        Function(4781, ref: true, "KnockAreaEffect", abbrev: "kae", .float, .float),
        Function(4782, ref: true, "InterruptCast"),
        Function(4783, "AddFormToFormList", .unknown(62, "Form"), .unknown(62, "Form")),
        Function(4784, "RevertFormList", .unknown(62, "Form")),
        Function(4785, "AddFormToLeveledList", .unknown(62, "Form"), .unknown(62, "Form"), .integer("Int"), .integer("Int")),
        Function(4786, "RevertLeveledList", .unknown(62, "Form")),
        Function(4787, "EPModSkillUsage_AdvanceObjectHasKeyword", .unknown(59, "Keyword")),
        Function(4788, "EPModSkillUsage_IsAdvanceAction", .unknown(80, "Skill Action")),
        Function(4789, "EPMagic_SpellHasKeyword", .unknown(59, "Keyword")),
        Function(4790, ref: true, "GetNoBleedoutRecovery"),
        Function(4791, ref: true, "SetNoBleedoutRecovery", .integer),
        Function(4792, "EPMagic_SpellHasSkill", .actorValue),
        Function(4793, "IsAttackType", .unknown(59, "Keyword")),
        Function(4794, ref: true, "IsAllowedToFly"),
        Function(4795, ref: true, "HasMagicEffectKeyword", .unknown(59, "Keyword")),
        Function(4796, ref: true, "IsCommandedActor"),
        Function(4797, ref: true, "IsStaggered"),
        Function(4798, ref: true, "IsRecoiling"),
        Function(4799, ref: true, "IsExitingInteractionQuick"),
        Function(4800, ref: true, "IsPathing"),
        Function(4801, ref: true, "GetShouldHelp", .actor),
        Function(4802, ref: true, "HasBoundWeaponEquipped", .unknown(68, "Casting Source")),
        Function(4803, ref: true, "GetCombatTargetHasKeyword", abbrev: "gcthk", .unknown(59, "Keyword")),
        Function(4804, "UpdateLevel", description: "Update the player's level based on current skill usage amounts."),
        Function(4805, ref: true, "GetCombatGroupMemberCount", abbrev: "gcgmc"),
        Function(4806, ref: true, "IsIgnoringCombat"),
        Function(4807, ref: true, "GetLightLevel", abbrev: "gll"),
        Function(4808, "SavePCFace", abbrev: "spf", .string),
        Function(4809, "SpellHasCastingPerk", .unknown(39, "Perk")),
        Function(4810, ref: true, "IsBeingRidden"),
        Function(4811, ref: true, "IsUndead"),
        Function(4812, "GetRealHoursPassed"),
        Function(4813, "UnequipAll"),
        Function(4814, ref: true, "IsUnlockedDoor"),
        Function(4815, ref: true, "IsHostileToActor", .actor),
        Function(4816, ref: true, "GetTargetHeight", .unknown(4, "TESObjectREFR"), description: "Get the delta on z between two references"),
        Function(4817, ref: true, "IsPoison", description: "Is the object a Poison potion"),
        Function(4818, ref: true, "WornApparelHasKeywordCount", .unknown(59, "Keyword")),
        Function(4819, ref: true, "GetItemHealthPercent"),
        Function(4820, ref: true, "EffectWasDualCast"),
        Function(4821, ref: true, "GetKnockStateEnum"),
        Function(4822, "DoesNotExist"),
    ]
    
}

